### PR TITLE
ES6

### PR DESCRIPTION
**Pull request by mpa-mxiang**
For this PR, I did:

- Use ES6 modules to write modular JavaScript.
- Learn how to use proper ES6 syntax.
- Understand improvements that ES6 brings to JavaScript.
- Use npm as a software package system.

### CODE REVIEW

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @mpa-mxiang,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [x] You didn't use the correct workflow, Kindly make sure that you used the correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by mpa-mxiang** [comment]
Thank you for mentioning it, I just changed the name.

**Comment by addod19** [comment]
### Hi @mpa-mxiang, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the file changes does not reflect the current project, we are suppose to use modules and not classes as we can see in the project description
Screenshot from 2023-05-01 21-20-54. Here is a [link](https://javascript.plainenglish.io/module-design-pattern-vs-classes-in-javascript-45568e74ad2a) where we can learn more about modules and how to implement it in this current project


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by amon-cofie — CHANGES_REQUESTED** [review]
Hi @mpa-mxiang , 👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not show the changes you made in the 'files changed' tab. I notice that this problem occurred while you tried to fix the problem that the previous reviewer pointed out about your use of GitHub flow. You can fix this easily by renaming your main branch ```git branch -m main <new name>```, Creating a new main branch, and opening a pull request from the old main branch which you renamed into the new main branch which you just created. This should ensure that all the changes you made in this milestone appear in on the 'files changed' tab 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
